CREATE ROLE lector WITH LOGIN PASSWORD 'lector123';

GRANT CONNECT ON DATABASE clinica_db TO lector;
GRANT USAGE ON SCHEMA public TO lector;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO lector;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO lector;
