services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: clinica_user
      POSTGRES_PASSWORD: clinica_pass
      POSTGRES_DB: clinica_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  dw:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: clinica_user
      POSTGRES_PASSWORD: clinica_pass
      POSTGRES_DB: clinica_db
    ports:
      - "5434:5432"
    volumes:
      - dwdata:/var/lib/postgresql/data
      - ./dw/init-scripts:/docker-entrypoint-initdb.d

  metabase:
    image: metabase/metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - dw
    volumes:
      - ./metabase-data:/metabase.db

volumes:
  pgdata:
  dwdata:
